### PR TITLE
Allow Blank Configs - Fixes #71

### LINKED ISSUE #71: Can we use blank config?
### What feature do you want to see added?

https://github.com/jenkinsci/pipeline-npm-plugin/blob/e2e393062d867effdcdf45b35c60c588d8c03217/src/main/java/com/github/timothydowney/plugins/pipeline/npm/WithNPMStepExecution.java#L128-L130

I just want to use the auth that is associated with the npmrc config, so my content is empty. Can you please allow for blank config files?

### Upstream changes

_No response_

### PR DESCRIPTION
**Pull request by Ya-shh**
Issue link: https://github.com/jenkinsci/pipeline-npm-plugin/issues/71

This pull request introduces a streamlined approach to handling empty .npmrc configurations within the WithNPMStepExecution class.
Introduced a straightforward warning log message for cases where the .npmrc config content is found to be blank, allowing the process to proceed without writing an empty file.
Maintained the essential functionality of writing the .npmrc file when valid content is provided, ensuring that the plugin's core functionality remains unaffected.

### Testing done:

testSettingsFromConfigWhenConfigNotFoundThenThrowAbortException - Test case to verify that the method throws an AbortException when the ConfigFiles.getByIdOrNull() method returns null. 

testSettingsFromConfigWhenConfigContentBlankThenPrintWarningAndReturn - Test case to verify that the method prints a warning message and returns without writing the file when the Config object has blank content. 

testSettingsFromConfigWhenConfigContentNonBlankThenWriteFile - Test case to verify that the method writes the file with the content of the Config object when the Config object has non-blank content.

### Tests:

package com.github.timothydowney.plugins.pipeline.npm;

import static org.junit.Assert.assertThrows;
import static org.junit.Assert.assertTrue;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import hudson.AbortException;
import hudson.FilePath;
import hudson.model.Run;
import hudson.model.TaskListener;
import org.jenkinsci.lib.configprovider.ConfigProvider;
import org.jenkinsci.lib.configprovider.model.Config;
import org.jenkinsci.plugins.configfiles.ConfigFiles;
import org.jenkinsci.plugins.workflow.steps.StepContext;
import org.junit.Before;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TemporaryFolder;
import org.jvnet.hudson.test.JenkinsRule;

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.nio.charset.StandardCharsets;

public class WithNPMStepExecutionTest {

    @Rule
    public JenkinsRule jenkinsRule = new JenkinsRule();

    @Rule
    public TemporaryFolder tempFolder = new TemporaryFolder();

    private StepContext context;
    private WithNPMStep step;
    private TaskListener listener;
    private FilePath ws;
    private Run<?, ?> build;
    private ByteArrayOutputStream baos;
    private PrintStream ps;

    @Before
    public void setUp() throws Exception {
        context = mock(StepContext.class);
        step = new WithNPMStep();
        listener = mock(TaskListener.class);
        ws = new FilePath(tempFolder.newFolder());
        build = mock(Run.class);
        baos = new ByteArrayOutputStream();
        ps = new PrintStream(baos, true, StandardCharsets.UTF_8.name());

        when(context.get(TaskListener.class)).thenReturn(listener);
        when(context.get(FilePath.class)).thenReturn(ws);
        when(context.get(Run.class)).thenReturn(build);
        when(listener.getLogger()).thenReturn(ps);
    }

    @Test
    public void testSettingsFromConfigWhenConfigNotFoundThenThrowAbortException() throws Exception {
        WithNPMStepExecution execution = new WithNPMStepExecution(context, step);
        String configId = "nonexistent-config-id";
        when(ConfigFiles.getByIdOrNull(build, configId)).thenReturn(null);

        AbortException exception = assertThrows(AbortException.class, () -> execution.settingsFromConfig(configId, ws.child(".npmrc")));
        assertTrue(exception.getMessage().contains("Could not find the NPM config file id:" + configId));
    }

    @Test
    public void testSettingsFromConfigWhenConfigContentBlankThenPrintWarningAndReturn() throws Exception {
        WithNPMStepExecution execution = new WithNPMStepExecution(context, step);
        String configId = "blank-content-config-id";
        Config config = mock(Config.class);
        when(config.content).thenReturn("");
        when(ConfigFiles.getByIdOrNull(build, configId)).thenReturn(config);

        execution.settingsFromConfig(configId, ws.child(".npmrc"));

        String output = baos.toString(StandardCharsets.UTF_8.name());
        assertTrue(output.contains("Warning: The NPM config file is empty. Proceeding without it."));
    }

    @Test
    public void testSettingsFromConfigWhenConfigContentNonBlankThenWriteFile() throws Exception {
        WithNPMStepExecution execution = new WithNPMStepExecution(context, step);
        String configId = "valid-config-id";
        Config config = mock(Config.class);
        ConfigProvider provider = mock(ConfigProvider.class);
        String fileContent = "registry=http://registry.npmjs.org/";
        when(config.content).thenReturn(fileContent);
        when(config.getDescriptor()).thenReturn(provider);
        when(provider.supplyContent(config, build, ws, listener, new ArrayList<>())).thenReturn(fileContent);
        when(ConfigFiles.getByIdOrNull(build, configId)).thenReturn(config);

        FilePath npmrcFile = ws.child(".npmrc");
        execution.settingsFromConfig(configId, npmrcFile);

        assertTrue(npmrcFile.exists());
        String writtenContent = npmrcFile.readToString();
        assertTrue(writtenContent.equals(fileContent));
    }
}

```[tasklist]
### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

### CODE REVIEW

**Comment by Ya-shh** [comment]
please review it !

**Comment by jonesbusy** [comment]
> please review it !

Please be patient. No need to be rude and asking with "!".

Your pull request had many issue because it was ready for review (target folder, no tests, no description).

I will review it when times permits

**Comment by Ya-shh** [comment]
Sorry,I have closed that request , this is a new request based on the checklist

**Comment by Ya-shh** [comment]
extremely sorry, I was just eager to know the review

**Comment by Ya-shh** [comment]
> > please review it !
> 
> Please be patient. No need to be rude and asking with "!".
> 
> Your pull request had many issue because it was ready for review (target folder, no tests, no description).
> 
> I will review it when times permits

Can you please close this as it will create a negative impact on the community. I am extremely sorry for that comment.

**Comment by Ya-shh** [comment]
If there are still any issues left, please let me know.

**Pull request closed without merging**
