### PR TITLE
Feature/modernize plugin

### PR DESCRIPTION
**Pull request by jonesbusy**
Modernize and refresh this plugin configuration (bom, dependabot etc...)

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by timothydowney** [comment]
Hi @jonesbusy -- I'm happy to pass the plugin along to you.  It's been quite a while since I've used this plugin.  I'm not exactly clear on the steps needed to allow you to adopt.

**Comment by jonesbusy** [comment]
Thanks! Your approval here is enough. I will ask to be added to this repository permission.

Regards,

**Comment by timothydowney** [comment]
Sure thing -- I am providing my approval for @jonesbusy to adopt this plugin.

@jonesbusy -- You're able to see that the build is failing due to:

```
Caused by: java.lang.UnsupportedClassVersionError: org/jenkinsci/maven/plugins/hpi/ValidateMojo has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

This is likely due to your JDK changes in the Jenkinsfile.

**Comment by jonesbusy** [comment]
> 
> This is likely due to your JDK changes in the Jenkinsfile.

Yes because this PR also drop support for JDK8 (with more recent Jenkins Core version).

**Comment by jonesbusy** [comment]
PR for permission here : https://github.com/jenkins-infra/repository-permissions-updater/pull/3125

**Pull request merged**
